import React, { createContext, useState, useContext, useEffect } from 'react';

const translations = {
  id: {
    // Navbar
    home: 'Beranda',
    about: 'Tentang',
    types: 'Tipe',
    benefits: 'Manfaat',
    featured: 'Unggulan',
    faq: 'Tanya Jawab',
    explore_map: 'Jelajahi Peta',
    login: 'Masuk',
    register: 'Daftar',
    logout: 'Keluar',
    account: 'Akun Saya',
    // Hero
    hero_title: 'Jelajahi Museum di ',
    hero_title_accent: 'Indonesia',
    hero_subtitle: 'Platform utama Anda untuk memetakan dan menemukan distribusi museum di seluruh nusantara. Filter berdasarkan provinsi, kategori, dan temukan harta karun budaya terdekat.',
    start_exploring: 'Mulai Menjelajah',
    find_near_me: 'Cari di Sekitar Saya',
    // About Museum
    foundation_tag: 'Pondasi Utama',
    what_is_museum: 'Apa itu ',
    museum_accent: 'Museum',
    museum_desc: 'Museum lebih dari sekadar bangunan yang berisi benda-benda kuno. Museum adalah lembaga hidup yang melestarikan memori kolektif kita, melindungi warisan budaya, dan menginspirasi generasi mendatang melalui penemuan manusia.',
    preserving_history: 'Melestarikan Sejarah',
    preserving_history_desc: 'Melindungi artefak tak ternilai dan menceritakan kisah-kisah peradaban masa lalu.',
    educational_spaces: 'Ruang Edukasi',
    educational_spaces_desc: 'Lingkungan interaktif di mana pembelajaran menjadi hidup di luar ruang kelas.',
    cultural_identity: 'Identitas Budaya',
    cultural_identity_desc: 'Menghubungkan generasi sekarang dengan akar leluhur dan warisan yang beragam.',
    art_science: 'Seni & Sains',
    art_science_desc: 'Menampilkan kreativitas manusia, inovasi, dan pemahaman kita tentang alam semesta.',
    museum_quote: '"Museum adalah pengelola kesadaran. Mereka memberi kita interpretasi sejarah, tentang bagaimana memandang dunia dan menempatkan diri kita di dalamnya."',
    // Benefits
    benefits_title: 'Kenapa Museum Itu Penting',
    benefits_subtitle: 'Temukan dampak positif museum bagi masyarakat dan pengembangan ilmu pengetahuan.',
    benefit_heritage: 'Melestarikan Warisan Budaya',
    benefit_heritage_desc: 'Menjaga harta karun nasional fisik dan non-fisik untuk masa depan.',
    benefit_education: 'Ruang Edukasi',
    benefit_education_desc: 'Menyediakan lingkungan belajar yang interaktif dan mendalam bagi siswa.',
    benefit_tourism: 'Mendukung Pariwisata Budaya',
    benefit_tourism_desc: 'Meningkatkan ekonomi lokal dengan menarik pengunjung domestik dan internasional.',
    benefit_research: 'Sumber Penelitian',
    benefit_research_desc: 'Berfungsi sebagai repositori penting untuk studi sejarah, ilmiah, dan artistik.',
    benefit_identity: 'Memperkenalkan Identitas Nasional',
    benefit_identity_desc: 'Menumbuhkan rasa memiliki dan kebanggaan yang mendalam terhadap warisan Indonesia kita.',
    bridge_to_knowledge: 'Jembatan Menuju Pengetahuan',
    bridge_to_knowledge_desc: 'Museum berfungsi sebagai institusi dinamis yang menghubungkan sejarah kita dengan rasa ingin tahu dunia modern yang tak ada habisnya.',
    // Types
    types_title: 'Kategori Museum yang Beragam',
    types_subtitle: 'Indonesia adalah rumah bagi beragam museum, masing-masing didedikasikan untuk melestarikan aspek unik dari identitas nasional kita. Apa yang akan Anda jelajahi hari ini?',
    cat_art: 'Seni & Budaya',
    cat_art_desc: 'Nikmati karya seni, tradisi, dan ekspresi budaya yang mencerminkan kekayaan nusantara.',
    cat_history: 'Sejarah',
    cat_history_desc: 'Jelajahi jejak masa lalu, dari kerajaan kuno hingga jalan Indonesia menuju kemerdekaan.',
    cat_science: 'Sains & Teknologi',
    cat_science_desc: 'Pelajari inovasi ilmiah dan kemajuan teknologi melalui koleksi interaktif edukatif.',
    cat_nature: 'Alam',
    cat_nature_desc: 'Temukan kekayaan flora, fauna, geologi, dan keajaiban lingkungan dari seluruh Indonesia.',
    cat_military: 'Militer',
    cat_military_desc: 'Pahami sejarah pertahanan dan perjuangan melalui artefak militer, strategi, dan kisah kepahlawanan.',
    cat_special: 'Khusus',
    cat_special_desc: 'Jelajahi tema unik seperti transportasi, musik, olahraga, atau koleksi tematik terkurasi lainnya.',
    // Category Literal Mapping
    'Seni & Budaya': 'Seni & Budaya',
    'Sejarah': 'Sejarah',
    'Sains & Teknologi': 'Sains & Teknologi',
    'Alam': 'Alam',
    'Militer': 'Militer',
    'Khusus': 'Khusus',
    'Museum': 'Museum',
    'Tidak Dikategorikan': 'Tidak Dikategorikan',
    // Featured
    featured_title: 'Museum Pilihan',
    featured_subtitle: 'Pilihan museum paling ikonik dan sering dikunjungi sebagai landmark budaya di seluruh negeri.',
    view_map: 'Lihat Peta',
    must_visit: 'Wajib Dikunjungi',
    learn_more: 'Pelajari lebih lanjut',
    // FAQ
    faq_title: 'Pertanyaan yang Sering Diajukan',
    faq_subtitle: 'Segala hal yang perlu Anda ketahui tentang misi kami dan dunia museum di Indonesia.',
    faq_1_q: 'Apa itu museum sebenarnya?',
    faq_1_a: 'Museum adalah lembaga yang merawat koleksi artefak dan benda lain yang memiliki kepentingan ilmiah, artistik, budaya, atau sejarah dan menyediakannya untuk dilihat publik melalui pameran.',
    faq_2_q: 'Mengapa museum penting bagi Indonesia?',
    faq_2_a: 'Indonesia adalah negara kepulauan dengan ratusan budaya, bahasa, dan sejarah panjang yang berbeda mulai dari kerajaan kuno hingga era kolonial. Museum membantu melestarikan keragaman yang luar biasa ini dan mengedukasi generasi mendatang tentang identitas mereka.',
    faq_3_q: 'Apakah semua museum hanya tentang benda sejarah?',
    faq_3_a: 'Sama sekali tidak! Ada museum sains, galeri seni kontemporer, museum transportasi, museum maritim, dan museum anak interaktif. Bentang alam museum sangat bervariasi.',
    faq_4_q: 'Dapatkah platform ini membantu saya menemukan museum terdekat?',
    faq_4_a: 'Ya, Anda dapat menggunakan layanan berbasis lokasi untuk menemukan museum di dekat Anda, memfilternya berdasarkan kategori dan provinsi, serta merencanakan kunjungan Anda dengan mudah.',
    // Map Page
    your_location: 'Lokasi Anda',
    filters_search: 'Filter & Pencarian',
    search_museum: 'Cari Museum',
    search_placeholder: 'Ketik nama museum...',
    province: 'Provinsi',
    all_provinces: 'Semua Provinsi',
    regency: 'Kabupaten / Kota',
    all_regencies: 'Semua Kabupaten/Kota',
    category: 'Kategori',
    all_categories: 'Semua Kategori',
    nearby_museums_title: 'Museum Terdekat',
    search_radius: 'Radius pencarian',
    use_my_location: 'Gunakan Lokasi Saya',
    disable_nearby: 'Nonaktifkan Nearby',
    back: 'Kembali',
    err_load_museums: 'Gagal memuat data museum',
    err_geolocation_unsupported: 'Browser tidak mendukung geolokasi',
    err_nearby_search: 'Gagal mencari museum terdekat',
    err_get_location: 'Gagal mendapatkan lokasi. Pastikan izin lokasi diaktifkan.',
    close_sidebar: 'Tutup sidebar',
    open_sidebar: 'Buka sidebar',
    // Detail Panel.Jsx
    no_review_yet: 'Belum ada ulasan untuk museum ini.',
    no_photo_yet: 'Belum ada foto kiriman pengunjung.',
    your_name: 'Nama Anda',
    tell_us_about_your_visit: 'Ceritakan tentang kunjungan Anda...',
    submit_review: 'Kirim Ulasan',
    upload_photo: 'Unggah Foto',
    share_your_experience: 'Bagikan Pengalaman Anda',
    must_login_review: 'Silakan masuk untuk mengirim ulasan',
    must_login_photo: 'Silakan masuk untuk mengunggah foto',
    museum_visit: 'Kunjungan museum',
    summary: 'ringkasan',
    review: 'ulasan',
    photo: 'foto',
    no_photo: 'Belum ada foto',
    province: 'Provinsi',
    regency: 'Kabupaten / Kota',
    description: 'Deskripsi',
    coordinate: 'Alamat Koordinat',
    no_description: 'Belum ada deskripsi untuk museum ini.',
    ticket_price: 'Harga Tiket',
    management: 'Kepengurusan',
    visit_website: 'Kunjungi Situs Web',
    official_website: 'Situs Web Resmi',
    get_route: 'Dapatkan Rute di Google Maps',
    not_available: 'Belum tersedia',
    // Form
    add_museum: 'Tambah Museum Baru',
    edit_museum: 'Edit Museum',
    name: 'Nama Museum',
    // Footer
    footer_desc: 'GeoMuse adalah platform navigasi museum terlengkap di Indonesia, menghubungkan Anda dengan warisan budaya melalui teknologi pemetaan modern.',
    rights_reserved: 'Hak Cipta Dilindungi.',
    quick_links: 'Tautan Cepat',
    contact_us: 'Hubungi Kami',
    // Stats Dashboard
    stats_title: 'Wawasan Museum',
    stats_subtitle: 'Analisis visual tentang distribusi dan keragaman museum di seluruh Indonesia.',
    chart_province_title: 'Museum per Provinsi',
    chart_province_desc: 'Distribusi jumlah museum berdasarkan provinsi.',
    chart_category_title: 'Museum per Kategori',
    chart_category_desc: 'Distribusi museum berdasarkan jenis kategori.',
    chart_regency_title: 'Top Kabupaten/Kota',
    chart_regency_desc: 'Kabupaten dengan jumlah museum terbanyak.',
    total_museum_label: 'Total Museum',
    total_province_label: 'Total Provinsi',
    total_regency_label: 'Total Kabupaten',
    total_category_label: 'Total Kategori',
    no_category_label: 'Tanpa Kategori',
    // Facts
    facts_title: 'Tahukah Anda?',
    facts_subtitle: 'Museum menyimpan cerita dan fakta luar biasa yang membentuk pemahaman kita tentang dunia. Berikut adalah sekilas tentang lanskap museum di Indonesia.',
    fact_1_val: '600+',
    fact_1_label: 'Museum di Indonesia',
    fact_1_desc: 'Tersebar di seluruh nusantara, melestarikan sejarah lokal dan nasional.',
    fact_2_val: 'Jutaan',
    fact_2_label: 'Pengunjung Tahunan',
    fact_2_desc: 'Wisatawan domestik dan internasional yang memperkaya wawasan mereka.',
    fact_3_val: '7+',
    fact_3_label: 'Kategori Beragam',
    fact_3_desc: 'Dari maritim hingga penerbangan, seni rupa hingga sejarah alam.',
    // About Platform
    platform_tag: 'Visi Platform',
    platform_title: 'Cara Baru Menemukan ',
    platform_title_accent: 'Warisan Kita',
    platform_desc: 'Kami sedang membangun platform paling komprehensif untuk memetakan dan menjelajahi distribusi museum di Indonesia. Saat ini adalah hub informasi, fitur-fitur mendatang akan mengubah cara Anda merencanakan perjalanan budaya.',
    feat_smart_filter: 'Filter Cerdas',
    feat_smart_filter_desc: 'Cari berdasarkan provinsi, kabupaten, atau kategori museum dengan mudah.',
    feat_loc_based: 'Berbasis Lokasi',
    feat_loc_based_desc: 'Temukan museum terdekat berdasarkan lokasi Anda saat ini secara instan.',
    feat_interactive: 'Peta Interaktif',
    feat_interactive_desc: 'Eksplorasi visual distribusi museum di seluruh Indonesia.',
    feat_guides: 'Panduan Detail',
    feat_guides_desc: 'Dapatkan harga tiket, jam buka, dan sorotan koleksi.',
    loading_data: 'Memuat data museum...',
    // Featured Museums Data
    fm_1_name: 'Museum Nasional Indonesia',
    fm_1_loc: 'Jakarta Pusat',
    fm_1_desc: 'Dikenal sebagai Gedung Gajah, menyimpan lebih dari 140.000 artefak prasejarah dan sejarah.',
    fm_2_name: 'Museum Angkut',
    fm_2_loc: 'Kota Batu, Jawa Timur',
    fm_2_desc: 'Museum transportasi modern pertama di Asia Tenggara, menampilkan mobil klasik dan zona tematik.',
    fm_3_name: 'Museum Tsunami Aceh',
    fm_3_loc: 'Banda Aceh',
    fm_3_desc: 'Karya arsitektur yang mengharukan untuk memperingati bencana tsunami 2004 dan menghormati para korban.',
    fm_4_name: 'Museum Ullen Sentalu',
    fm_4_loc: 'Yogyakarta',
    fm_4_desc: 'Melihat sekilas seni dan budaya dinasti Mataram dalam suasana hutan yang indah.',
  },
  en: {
    // Navbar
    home: 'Home',
    about: 'About',
    types: 'Types',
    benefits: 'Benefits',
    featured: 'Featured',
    faq: 'FAQ',
    explore_map: 'Explore Map',
    login: 'Login',
    register: 'Register',
    logout: 'Logout',
    account: 'My Account',
    // Hero
    hero_title: 'Explore Indonesia\'s ',
    hero_title_accent: 'Museums',
    hero_subtitle: 'Your ultimate platform for mapping and discovering museum distributions across the archipelago. Filter by province, category, and find the nearest cultural treasures.',
    start_exploring: 'Start Exploring',
    find_near_me: 'Find Near Me',
    // About Museum
    foundation_tag: 'The Foundation',
    what_is_museum: 'What is a ',
    museum_accent: 'Museum',
    museum_desc: 'A museum goes beyond simply being a building filled with ancient objects. It is a living, breathing institution that preserves our collective memory, safeguards our cultural heritage, and inspires future generations through human discovery.',
    preserving_history: 'Preserving History',
    preserving_history_desc: 'Safeguarding invaluable artifacts and telling stories of civilizations past.',
    educational_spaces: 'Educational Spaces',
    educational_spaces_desc: 'Interactive environments where learning comes alive beyond the classroom.',
    cultural_identity: 'Cultural Identity',
    cultural_identity_desc: 'Connecting present generations with their ancestral roots and diverse heritage.',
    art_science: 'Art & Science',
    art_science_desc: 'Showcasing human creativity, innovation, and our understanding of the universe.',
    museum_quote: '"Museums are managers of consciousness. They give us an interpretation of history, of how to view the world and locate ourselves in it."',
    // Benefits
    benefits_title: 'Why Museums Matter',
    benefits_subtitle: 'Discover the positive impact of museums on society and the development of knowledge.',
    benefit_heritage: 'Preserving Cultural Heritage',
    benefit_heritage_desc: 'Safeguarding physical and intangible national treasures for the future.',
    benefit_education: 'Educational Spaces',
    benefit_education_desc: 'Providing interactive and immersive learning environments for students.',
    benefit_tourism: 'Supporting Cultural Tourism',
    benefit_tourism_desc: 'Boosting local economies by attracting domestic and international visitors.',
    benefit_research: 'Sources for Research',
    benefit_research_desc: 'Serving as vital repositories for historical, scientific, and artistic study.',
    benefit_identity: 'Introducing National Identity',
    benefit_identity_desc: 'Fostering a deep sense of belonging and pride in our Indonesian heritage.',
    bridge_to_knowledge: 'A Bridge to Knowledge',
    bridge_to_knowledge_desc: 'Museums serve as dynamic institutions connecting our history to the modern world\'s endless curiosity.',
    // Types
    types_title: 'Diverse Museum Categories',
    types_subtitle: 'Indonesia is home to a vast array of museums, each dedicated to preserving a unique facet of our national identity. What will you explore today?',
    cat_art: 'Art & Culture',
    cat_art_desc: 'Enjoy artistic works, traditions, and cultural expressions that reflect the richness of the archipelago.',
    cat_history: 'History',
    cat_history_desc: 'Explore the traces of the past, from ancient kingdoms to Indonesia\'s road to independence.',
    cat_science: 'Science & Technology',
    cat_science_desc: 'Learn about scientific innovation and technological progress through educational interactive collections.',
    cat_nature: 'Nature',
    cat_nature_desc: 'Discover rich flora, fauna, geology, and environmental wonders from across Indonesia.',
    cat_military: 'Military',
    cat_military_desc: 'Understand the history of defense and struggle through military artifacts, strategy, and heroic stories.',
    cat_special: 'Special',
    cat_special_desc: 'Explore unique themes such as transportation, music, sports, or other curated thematic collections.',
    // Category Literal Mapping
    'Seni & Budaya': 'Art & Culture',
    'Sejarah': 'History',
    'Sains & Teknologi': 'Science & Technology',
    'Alam': 'Nature',
    'Militer': 'Military',
    'Khusus': 'Special',
    'Museum': 'Museum',
    'Tidak Dikategorikan': 'Uncategorized',
    // Featured
    featured_title: 'Featured Museums',
    featured_subtitle: 'A curated selection of the most iconic and frequently visited cultural landmarks across the nation.',
    view_map: 'View Map',
    must_visit: 'Must Visit',
    learn_more: 'Learn more',
    // FAQ
    faq_title: 'Frequently Asked Questions',
    faq_subtitle: 'Everything you need to know about our mission and the world of Indonesian museums.',
    faq_1_q: 'What is a museum exactly?',
    faq_1_a: 'A museum is an institution that cares for a collection of artifacts and other objects of scientific, artistic, cultural, or historical importance and makes them available for public viewing through exhibits.',
    faq_2_q: 'Why are museums important for Indonesia?',
    faq_2_a: 'Indonesia is an archipelago with hundreds of distinct cultures, languages, and long histories spanning ancient kingdoms to colonial eras. Museums help preserve this immense diversity and educate future generations about their identity.',
    faq_3_q: 'Are all museums only about historical objects?',
    faq_3_a: 'Not at all! There are science museums, contemporary art galleries, transportation museums, maritime museums, and interactive children\'s museums. The landscape of museums is incredibly varied.',
    faq_4_q: 'Can this platform help me find the nearest museum?',
    faq_4_a: 'Yes, you can use location-based services to find museums near you, filter them by category and province, and plan your visits easily.',
    // Map Page
    your_location: 'Your Location',
    filters_search: 'Filter & Search',
    search_museum: 'Search Museum',
    search_placeholder: 'Type museum name...',
    province: 'Province',
    all_provinces: 'All Provinces',
    regency: 'Regency / City',
    all_regencies: 'All Regencies/Cities',
    category: 'Category',
    all_categories: 'All Categories',
    nearby_museums_title: 'Nearby Museums',
    search_radius: 'Search radius',
    use_my_location: 'Use My Location',
    disable_nearby: 'Disable Nearby',
    back: 'Back',
    err_load_museums: 'Failed to load museum data',
    err_geolocation_unsupported: 'Browser does not support geolocation',
    err_nearby_search: 'Failed to search nearby museums',
    err_get_location: 'Failed to get location. Make sure location permissions are enabled.',
    close_sidebar: 'Close sidebar',
    open_sidebar: 'Open sidebar',
    // Detail Panel
    no_photo_yet: 'No photo yet..',
    no_review_yet: 'No review yet',
    share_your_experience: 'Share Your Experience',
    your_name: 'Your Name',
    tell_us_about_your_visit: 'Tell us about your visit...',
    submit_review: 'Submit Review',
    upload_photo: 'Upload Photo',
    must_login_review: 'Please login to post a review',
    must_login_photo: 'Please login to upload a photo',
    museum_visit: 'Museum visit',
    summary: 'summary',
    review: 'review',
    photo: 'photo',
    province: 'Province',
    no_photo: 'No photo available',
    regency: 'Regency / City',
    coordinate: 'Coordinate Address',
    description: 'Description',
    no_description: 'No description available for this museum yet.',
    ticket_price: 'Ticket Price',
    management: 'Management',
    visit_website: 'Visit Website',
    official_website: 'Official Website',
    get_route: 'Get Route on Google Maps',
    not_available: 'Not available',
    // Form
    add_museum: 'Add New Museum',
    edit_museum: 'Edit Museum',
    name: 'Museum Name',
    // Footer
    footer_desc: 'GeoMuse is the most complete museum navigation platform in Indonesia, connecting you with cultural heritage through modern mapping technology.',
    rights_reserved: 'All Rights Reserved.',
    quick_links: 'Quick Links',
    contact_us: 'Contact Us',
    // Stats Dashboard
    stats_title: 'Museum Insights',
    stats_subtitle: 'Visual analysis of museum distribution and diversity across Indonesia.',
    chart_province_title: 'Museums per Province',
    chart_province_desc: 'Distribution of museum counts by province.',
    chart_category_title: 'Museums per Category',
    chart_category_desc: 'Distribution of museums by category type.',
    chart_regency_title: 'Top Regencies/Cities',
    chart_regency_desc: 'Regencies with the highest number of museums.',
    total_museum_label: 'Total Museums',
    total_province_label: 'Total Provinces',
    total_regency_label: 'Total Regencies',
    total_category_label: 'Total Categories',
    no_category_label: 'Uncategorized',
    // Facts
    facts_title: 'Did You Know?',
    facts_subtitle: 'Museums hold incredible stories and facts that shape our understanding of the world. Here are just a few glimpses into Indonesia\'s museum landscape.',
    fact_1_val: '600+',
    fact_1_label: 'Museums in Indonesia',
    fact_1_desc: 'Scattered across the archipelago, preserving local and national histories.',
    fact_2_val: 'Millions',
    fact_2_label: 'Annual Visitors',
    fact_2_desc: 'Domestic and international tourists enriching their minds.',
    fact_3_val: '7+',
    fact_3_label: 'Diverse Categories',
    fact_3_desc: 'From maritime to aviation, fine arts to natural history.',
    // About Platform
    platform_tag: 'Platform Vision',
    platform_title: 'A New Way to Discover ',
    platform_title_accent: 'Our Heritage',
    platform_desc: 'We are building the most comprehensive platform to map and explore museum distributions in Indonesia. While currently an informational hub, upcoming features will transform how you plan your cultural journeys.',
    feat_smart_filter: 'Smart Filtering',
    feat_smart_filter_desc: 'Easily search by province, regency, or museum category.',
    feat_loc_based: 'Location Based',
    feat_loc_based_desc: 'Find the nearest museums based on your current location instantly.',
    feat_interactive: 'Interactive Maps',
    feat_interactive_desc: 'Visual exploration of museum distributions across Indonesia.',
    feat_guides: 'Detailed Guides',
    feat_guides_desc: 'Get ticket prices, opening hours, and collection highlights.',
    loading_data: 'Loading museum data...',
    // Featured Museums Data
    fm_1_name: 'National Museum of Indonesia',
    fm_1_loc: 'Jakarta Pusat',
    fm_1_desc: 'Affectionately known as the Elephant Building, housing over 140,000 prehistoric and historical artifacts.',
    fm_2_name: 'Museum Angkut',
    fm_2_loc: 'Kota Batu, Jawa Timur',
    fm_2_desc: 'Southeast Asia\'s first modern transportation museum, featuring classic cars and thematic zones.',
    fm_3_name: 'Aceh Tsunami Museum',
    fm_3_loc: 'Banda Aceh',
    fm_3_desc: 'A poignant architectural masterwork commemorating the 2004 tsunami disaster and honoring its victims.',
    fm_4_name: 'Ullen Sentalu Museum',
    fm_4_loc: 'Yogyakarta',
    fm_4_desc: 'An intimate glimpse into the art and culture of the Mataram dynasty within a beautiful forest setting.',
  }
};

const LanguageContext = createContext();

export const LanguageProvider = ({ children }) => {
  const [lang, setLang] = useState(localStorage.getItem('lang') || 'id');

  useEffect(() => {
    localStorage.setItem('lang', lang);
  }, [lang]);

  const t = (key) => {
    return translations[lang][key] || key;
  };

  const toggleLanguage = () => {
    setLang(prev => (prev === 'id' ? 'en' : 'id'));
  };

  return (
    <LanguageContext.Provider value={{ lang, t, toggleLanguage }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => useContext(LanguageContext);
